### ISSUE TITLE
Database size

### ISSUE THREAD

**Issue by alexandre-mbm** [ninetwentyfour/Hospitium#23]
The _free_ plan of Heroku supports 10.000 records only.
How to estimate if this would be enough for at least a shelter with 150 animals?
How many records of database the hospitum.co have today? How many shelters and animals?
I know there are several other entity types: vets, shots, weights... But I want have a notion only.

**Comment by ninetwentyfour** [comment]
You can run for quite a while on the heroku free plan. hospitium.co ran with the free plan for a couple years.

For a single shelter with 150 animals you will have more than enough db space.

**Comment by alexandre-mbm** [comment]
Do you remember about how much was the size of the instance when the Heroku free plan has become insufficient?

**Comment by alexandre-mbm** [comment]
When I implant my small instance, I will do [dataclip](https://devcenter.heroku.com/articles/dataclips) with `count()`'s selects.
