### ISSUE TITLE
Post to animal sites

### ISSUE THREAD

**Issue by alexandre-mbm** [ninetwentyfour/Hospitium#24]
- [ ] [Petfinder](https://www.petfinder.com/)
- [ ] [Adopt-a-Pet](http://www.adoptapet.com/)
  - [ ] add note* about security
- [x] Wordpress
  - [ ] add note* about security

\* Note that speaks that they should create accounts for this, with unique usernames and strong passwords, with as little permissions as possible. Not admin accounts! Just ability to posting.

---

@ninetwentyfour, did you have done a lot of this issue, did not you?

**Comment by ninetwentyfour** [comment]
Yep, this is done.
