### ISSUE TITLE
Mailchimp

### ISSUE THREAD

**Issue by alexandre-mbm** [ninetwentyfour/Hospitium#35]
Mailchimp integration for e-mail list.

**Comment by alexandre-mbm** [comment]
Is this done?! Or do you have given up?

**Comment by ninetwentyfour** [comment]
More like something I won't end up doing. If I did, I would use sendgrid now :)

**Comment by alexandre-mbm** [comment]
Why? MailChimp can send 12,000 emails _free_.

**Comment by ninetwentyfour** [comment]
I work at sendgrid :)

**Comment by alexandre-mbm** [comment]
I had seen and forgotten.
