### ISSUE TITLE
Improve the organizations's public pages

### ISSUE THREAD

**Issue by alexandre-mbm** [ninetwentyfour/Hospitium#45]
- [ ] let organizations add donate links to public pages ‒ **and the issue #46?**
- [ ] mark what fields are public ‒ **in organizations's public pages only?**

**Comment by alexandre-mbm** [comment]
@ninetwentyfour, do you have restricted your scope, is it?

**Comment by ninetwentyfour** [comment]
Yeah, a bit. That list was mostly a stream of ideas that was created pretty early on. Some of the things are no longer relevant or are ok as is for now.
