### ISSUE TITLE
Question about PostgreSQL, Redis and Memcache

### ISSUE THREAD

**Issue by alexandre-mbm** [ninetwentyfour/Hospitium#54]
What does make what? I understand that the PostgreSQL is for persistency. But are Redis and Memcache used together? How and why? In case of you don't respond me, I will study the code yet.

**Comment by alexandre-mbm** [comment]
@ninetwentyfour, I'm managing the knowledge of my settings in a document that already have _9 pages_. Lack only solve this issue, I believe. I get it the Puma and the basics of application's design.

I am able to open issues to fix little things and I will do as soon as possible.

**Is Redis used for Juggernaut and Memcached for cache, is this?**

**Comment by ninetwentyfour** [comment]
Yeah, you are right, redis is for juggernaut. Diagram looks pretty correct.
