### ISSUE TITLE
Juggernaut → SSEs ?

### ISSUE THREAD

**Issue by alexandre-mbm** [ninetwentyfour/Hospitium#55]
`SSEs` = `HTML5 Server-Sent Events`

See "[Killing a library](http://blog.alexmaccaw.com/killing-a-library)" by the Juggernaut author. July 11, 2012.

---

More: [Stream Updates with Server-Sent Events](http://www.html5rocks.com/en/tutorials/eventsource/basics/). By Eric Bidelman. November 30th, 2010.

**Comment by alexandre-mbm** [comment]
The [Juggernaut's author](/maccman/juggernaut/issues/135#issuecomment-21321205) wrote a [Sinatra pubsub extension](/maccman/sinatra-pubsub) for who want a high abstraction.

**Comment by ninetwentyfour** [comment]
Yeah, replacing juggernaut has been on my todo list for a while. I'm open to discussion on what should replace it.

**Comment by alexandre-mbm** [comment]
For now I can not pursue this matter. I need to run a first version at Cadanimal.
